# Generated by Django 4.0.4 on 2023-04-26 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='worker',
        ),
        migrations.AddField(
            model_name='branch',
            name='delivery',
            field=models.ManyToManyField(blank=True, related_name='deliverys', to=settings.AUTH_USER_MODEL),
        ),
    ]
