# Generated by Django 4.0.4 on 2023-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_courier_delivery_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
