# Generated by Django 4.0.4 on 2023-04-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
