# Generated by Django 4.0.4 on 2023-04-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_report_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
