# Generated by Django 4.0.4 on 2023-04-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_report_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='report',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='report',
            name='customer',
        ),
    ]
