# Generated by Django 4.0.4 on 2023-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_remove_report_branch_remove_report_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, related_name='reports', to='branch.report'),
        ),
    ]
