# Generated by Django 4.0.4 on 2023-04-29 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0009_branch_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.courier'),
        ),
        migrations.AddField(
            model_name='report',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reports', to='branch.report'),
        ),
    ]
