# Generated by Django 4.0.4 on 2023-04-29 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_report_courier_report_customer_alter_branch_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, null=True),
        ),
    ]
