# Generated by Django 4.0.4 on 2023-04-29 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0011_branch_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
