# Generated by Django 4.0.4 on 2023-04-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0012_alter_branch_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='present',
            field=models.ForeignKey(default='5673291', null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
